name: Compile and run tests

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    container: "quay.io/centos/centos:stream9"

    steps:
      - uses: actions/checkout@v2

      - name: Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel
          dnf -y clean all

      - name: âš™ï¸ Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
          echo $PATH:"$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: ðŸ“Ž Run Linters
        run: |
          cargo clippy --release -- -D warnings
          cargo fmt --all -- --check
          cargo doc --no-deps

      - name: ðŸ”¨ Build (Debug)
        run: cargo build --verbose

      - name: ðŸ”¨ Build (Release)
        run: cargo build --release --verbose

      - name: ðŸ§ª Run Unit Tests
        run: cargo test --release --bins --lib

  integration-tests:
    strategy:
      matrix:
        container: ["registry.fedoraproject.org/fedora:38", "quay.io/centos/centos:stream9"]
    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel
          dnf -y clean all

      - name: âš™ï¸ Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
          echo $PATH:"$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: ðŸ§ª Run Integration Tests
        run: |
          cargo test --test '*' --release --all-features
